---
.docker:
  stage: build
  image: docker:stable
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: generate
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG -f dockerfiles/$IMAGE_TAG.Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG

.docker-buildx:
  extends: .docker
  image: jdrouet/docker-with-buildx:stable
  script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --driver=docker-container --use
    - docker buildx build . --target=test
        --cache-to type=local,dest=.buildx-cache
        --file dockerfiles/$IMAGE_TAG.Dockerfile
        --platform $PLATFORMS
    - docker buildx build . --target=final --push
        --tag $CI_REGISTRY_IMAGE:$IMAGE_TAG
        --cache-from type=local,src=.buildx-cache
        --file dockerfiles/$IMAGE_TAG.Dockerfile
        --platform $PLATFORMS
  cache:
    key: buildx
    paths: [.buildx-cache]

.alias:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - docker pull $CI_REGISTRY_IMAGE:$SRC_TAG
    - docker tag $CI_REGISTRY_IMAGE:$SRC_TAG $CI_REGISTRY_IMAGE:$DST_TAG
