---
.docker:
  stage: build
  image: docker:stable
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: generate
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG -f dockerfiles/$IMAGE_TAG.Dockerfile .
    - docker run -t -v $PWD/tests:/tests $CI_REGISTRY_IMAGE:$IMAGE_TAG /tests/run.sh $CLANG_VERSION
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG

.alias:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - docker pull $CI_REGISTRY_IMAGE:$SRC_TAG
    - docker tag $CI_REGISTRY_IMAGE:$SRC_TAG $CI_REGISTRY_IMAGE:$DST_TAG
